# Website info
title: miltonolaf
email: hey@miltonolaf.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog

url: https://miltonolaf.com # the base hostname & protocol for your site, e.g. http://example.com
lang: es_MX
# Social users - twitter, instagram, github, gitlab, codepen profile, youtube and facebook
twitter:
  username: olafmilton
social:
  twitter: olafmilton
  github: miltonolaf

disqus: miltonolaf
analytics_id: UA-115008234-2

author:
  name: Milton Olaf Paredes
  twitter: olafmilton

favicon: favicon.png # favicon name in assets/img/

permalink: /:year/:month/:title/

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  profile: false
  blanklines: true
  startings: [html, head, body]

# Build settings

algolia:
  application_id: 3CXOFC7X8Y
  index_name: blog
  search_only_api_key: a53c7f9c8141b850e2cce55dad73eb3b

markdown: kramdown
kramdown:
  auto_ids: true

remote_theme: miltonolaf/another

defaults:
  -
    scope:
      type: "pages"
    values:
      layout: "page"
      page_title: true
      content_width: "default"
      post_content: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .git*
  - .gitignore
  - vendor
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
