# Website info
title: Milton Olaf
email: hey@miltonolaf.com
description: > # this means to ignore newlines until "baseurl:"
  Milton Olaf Paredes es un desarrollador de software y fanático de las ciencias de la computación, Mexicano, que disfruta escribir y enseñar sobre temas de su interes.

baseurl: "" # the subpath of your site, e.g. /blog

url: https://miltonolaf.com # the base hostname & protocol for your site, e.g. http://example.com
lang: es_MX
paginate: 6
paginate_path: /posts/:num/
# Social users - twitter, instagram, github, gitlab, codepen profile, youtube and facebook
twitter:
  username: olafmilton
social:
  twitter: olafmilton
  github: miltonolaf
  feed: /feed.xml

disqus: miltonolaf
analytics_id: UA-115008234-2

author:
  name: Milton Olaf Paredes
  twitter: olafmilton

favicon: favicon.png # favicon name in assets/img/

permalink: /:year/:month/:title/

# Compress html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  startings: [html, head, body]

# Assets - We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed
# Build settings

algolia:
  application_id: 3CXOFC7X8Y
  index_name: blog
  search_only_api_key: a53c7f9c8141b850e2cce55dad73eb3b

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .git*
  - .gitignore
  - vendor
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-toc
